# These are supported funding model platforms

github: faisalaffan
patreon: faisalaffan
open_collective: chainnusa
ko_fi: faisalaffan
tidelift: npm/chainnusa
community_bridge: chainnusa
liberapay: faisalaffan
issuehunt: faisalaffan
lfx_crowdfunding: chainnusa
polar: faisalaffan
buy_me_a_coffee: faisalaffan
thanks_dev: faisalaffan
custom:
  - https://saweria.co/faisalaffan
  - https://trakteer.id/faisalaffan
